### ISSUE TITLE
Fails In Windows

### ISSUE THREAD

**Issue by morethanfire** [Urthen/case-sensitive-paths-webpack-plugin#1]
On Windows this plugin fails, because of https://github.com/Urthen/case-sensitive-paths-webpack-plugin/blob/master/index.js#L42 is looking for only a mac style path and not windows.

**Comment by Urthen** [comment]
Resolved by #2

**Comment by Urthen** [comment]
@aggieben @morethanfire Patch v1.0.1 published to NPM.
