### ISSUE TITLE
Not working on Mac OSX

### ISSUE THREAD

**Issue by ChrisCates** [Urthen/case-sensitive-paths-webpack-plugin#11]
```
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/chriscates/projects/Custom-Box-Builder/src/Components/Steps/StepContainer.js` does not match the corresponding path on disk `components`.
[0]  @ ./src/routes.js 43:21-64
```

Not sure how to debug this. Basically `components` is lowercase... and for some weird reason all of these things throw errors.

**Comment by Urthen** [comment]
What is the correct casing of the path on disk? Assuming everything else is working correctly, the plugin thinks the correct path is `/Users/chriscates/projects/Custom-Box-Builder/src/components`

**Comment by ChrisCates** [comment]
```
/Users/chriscates/projects/Custom-Box-Builder/src/components
```

Here you go @Urthen

**Comment by Urthen** [comment]
Looks like you're attempting to import/require a module, but not specifying the correct case. The purpose of this plugin is to detect and prevent this situation as it can cause your build to fail on other operating systems that are case-sensitive. Somewhere you're attempting to import `Components/Steps/StepContainer.js` when you should be importing `components`. Check the rest of the path as well - it might be `steps` and `stepcontainer.js`, the plugin only warns about one at a time.

**Comment by ChrisCates** [comment]
Thanks for proof reading that!
You the man @Urthen
