### ISSUE TITLE
Non-issue causing warnings in Windows

### ISSUE THREAD

**Issue by JasonGoemaat** [Urthen/case-sensitive-paths-webpack-plugin#16]
This plugin is great for finding those errors, but it also triggers on different cases in parent directories on Windows that don't affect the actual build.  For instance I might have a `C:\Git\My-Project` folder, but in development I might `cd \git\my-project`.  Something in a build for 'create-react-app' is causing this because some modules are loaded with an absolute path (including '~' inside).  It would be nice if it could ignore directories outside the root of the project.

**Comment by Urthen** [comment]
This has become a common problem all of a sudden and I'm not sure why. Right now I'm not sure the best way to determine the root of the project, but I'll take a stab at it. If I can figure out a consistent way to figure out the project root I'll ignore casing above that point.

**Comment by Urthen** [comment]
Reported as resolved in referenced issue.
