### ISSUE TITLE
Error when new file is created

### ISSUE THREAD

**Issue by caesarsol** [Urthen/case-sensitive-paths-webpack-plugin#17]
When I create a new file while the server is running, and modify another one to refer to it, the plugin thinks the file doesn't exist and throws an error.

I have a test case to reproduce it, posting it in a few hours.

**Comment by caesarsol** [comment]
@Urthen I think it has to do with the FS caching by the plugin, could it be?

**Comment by Urthen** [comment]
Possible. Originally it was supposed to re-check the FS if a file wasn't found in the cache, but I had a big PR recently and it might have affected that. I'll look into it.

**Comment by caesarsol** [comment]
@Urthen here is the failing test: https://github.com/caesarsol/case-sensitive-paths-webpack-plugin/commit/41f11a50a2d1552810da34ce0b29d9fa4e3459e6

(I refactored something in testing code in the preceding commit)

**Comment by caesarsol** [comment]
Do you have any hint in fixing it?

**Comment by msuzoagu** [comment]
@Urthen Having the same issue and not sure how to fix. Would appreciate feedback. Thanks.

**Comment by caesarsol** [comment]
@msuzoagu Temporarily just restart the dev server :)

**Comment by Urthen** [comment]
Published 2.1.0 which should fix this. Can you give it a test?

**Comment by Urthen** [comment]
Reported as resolved elsewhere, closing.
