### ISSUE TITLE
Increase verbosity for "Module not found" errors

### ISSUE THREAD

**Issue by caesarsol** [Urthen/case-sensitive-paths-webpack-plugin#18]
Hello @Urthen,
do you think something like this is in scope with your module?

https://github.com/facebookincubator/create-react-app/issues/1278

Thank you!

**Comment by Urthen** [comment]
Hi @caesarsol -

Could you describe in more detail exactly what functionality you're looking for?

Thanks!

**Comment by Urthen** [comment]
I believe this is a duplicate of #19, if not please add more info and re-open.
