### ISSUE TITLE
CaseSensitive breaks on Mac OS 10.13

### ISSUE THREAD

**Issue by calumbutler** [Urthen/case-sensitive-paths-webpack-plugin#23]
Using this plugin in multiple environments, but this plugin breaks on Mac OS 10.13. If i disable the plugin my build completes and my app works.
```
Module not found: `/Users/calum/Sites/labbook-ui/src/JS/config.js` does not match the corresponding path on disk `js`.
```

```
resolve
    alias: {
      'react-native': 'react-native-web',
      'Components': path.resolve(__dirname, '../src/js/components/'),
      'Mutations': path.resolve(__dirname, '../src/js/mutations/'),
      'JS': path.resolve(__dirname, '../src/js/')

    }
}
```

Using: 
webpack2.2
Node v6.11.1
case-sensitive-paths-webpack-plugin@2.1.1

**Comment by Urthen** [comment]
Hi @calumbutler,

I think things might be getting confused by the alias of 'JS' to 'js'. Not positive though. If your project is public, could you send me the link? Taking a look at the structure might give me a better idea.

**Comment by calumbutler** [comment]
Unfortunately my project is private, I will create a skeleton project and send a link on to you.

**Comment by calumbutler** [comment]
Ran some high sierra updates, this has fixed the issue.

**Comment by Urthen** [comment]
Glad to hear it, closing the issue.
