### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by dylang** [Urthen/case-sensitive-paths-webpack-plugin#29]
Hi - great plugin!

Webpack 4 has changed some of the API's and now results in a deprecation warning. Just thought you'd like to know. 

Thanks for the great work!

**Comment by Urthen** [comment]
Merged #31 and released 2.1.2 which should resolve this. Let me know if it doesn't as I don't actually have any projects using Webpack 4 right now, but Travis says it works 👍

**Comment by nmschulte** [comment]
v2.1.2 seems to resolve the issue for me.  Thanks!

**Comment by zhangwentao** [comment]
It seems doesn't ok
![1521170346561](https://user-images.githubusercontent.com/900931/37502030-e2842a0a-290b-11e8-8456-e58598bcbba0.jpg)

**Comment by Urthen** [comment]
@zhangwentao Did you update this plugin to v2.1.2? Seems it has solved this issue for other users.

**Comment by nmschulte** [comment]
@zhangwentao also note that other plugins and codes may be using the deprecated API still, producing the warning.
