### ISSUE TITLE
Module not found while using storybook

### ISSUE THREAD

**Issue by bnbarak** [Urthen/case-sensitive-paths-webpack-plugin#33]
# Bug Report

## Description 
Getting 
```Module not found: Error: [CaseSensitivePathsPlugin] `/Users/xxx/yyy/webapp/src/components/github/GithubModal.js` does not match the corresponding path on disk `Github`.```
### Details
I'm having some issues with specific paths while using storybook.
The React (v16) app works well, but the storybook throughs ` Module not found: Error: [CaseSensitivePathsPlugin]` on the path:
 - `/Users/xxx/YYY/webapp/src/components/github/GithubModal.js`

Two things to keep in mind:
 1. when I copy paste the path to a browser's url the file is there.
 2. In the path the `YYY` part has a dot in it, i.e `aaa.bbb`
 3. The React app is working
 4. Storybook works on other machines (High Sierra)

### Versions
 - Webpack: 3.11.0
 - OSX El Capitan 10.11.6
 - React 16.3.1
 - Storybook/react: 3.4.4
 - case-sensitive-paths-webpack-plugin: 2.1.2 (from storybook's `packages.json`)

**Comment by Urthen** [comment]
Hey there,

What is the exact import or require statement? Does it require `github` or `Github`? And does that match what is on the disk?

Some users have reported problems where a case has changed on one machine and supposedly committed, but Git didn't pick up on it, so on other machines the casing of the require statement and file on disk is inconsistent.

**Comment by Urthen** [comment]
@bnbarak I'm still waiting on more information, I can't help you without knowing what is being required and whether or not the file reported in the console actually matches the file casing on disk.

**Comment by bnbarak** [comment]
Sorry for the delay. A week latter I updated libraries and it got solved.

Thank you!
