### ISSUE TITLE
Question: Use with create-react-app without ejecting? Possible?

### ISSUE THREAD

**Issue by erikfunkis** [Urthen/case-sensitive-paths-webpack-plugin#35]
As far as I can tell, this doesn't seem to be possible, since the webpack config files are not exposed in create-react-app (so you can't register plugins). Maybe this is a stupid question, but is there maybe a webpack-independent implementation that you know of? If not, is it possible (easy?) to modify your code to be webpack independent? I guess the tricky part would be to extract all the file-paths from the project code base?

Thankful for any help or pointers! And thanks for developing and maintaining this plugin! I've used the plugin before (on a project where we weren't so afraid to eject) and it's great!

**Comment by Urthen** [comment]
Hey Erik!

Good news: This plugin actually comes bundled with the default create-react-app installation.

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/package.json#L33

If that doesn't answer your question though:

This project relies on plugging in to Webpack's module resolution, so I imagine it isn't possible to add to a project in any other way besides adding it to Webpack's config.

**Comment by erikfunkis** [comment]
Thanks! That _is_ good news! :)  
I guess our problem must have been unrelated then! If I had to guess, a colleague of mine must have made the filename changes locally (to fix the error from your plugin) but then missed to actually commit them.  Understandable, since, on the Mac filesystem we use, committing such changes involves some extra steps (git mv -f path/onlyLower path/onlylower) for git to even recognize a change has been made.

Thanks again for a great plugin!

**Comment by Urthen** [comment]
Yeah, git not always correctly picking up on case-only changes seems to be a common problem. Hope everything works out!
