### ISSUE TITLE
Question: Will this work for typescript?

### ISSUE THREAD

**Issue by gbminnock** [Urthen/case-sensitive-paths-webpack-plugin#43]
Hey just wondering if this works for typescript? I've installed and run but can only see output ~ _Reading Directory ..._
Seems to be node_module folders and not hitting my src directory.

Having some issues because I develop on windows and build on linux. 

Thanks.

**Comment by Urthen** [comment]
To be perfectly frank, I don't know. I don't use Typescript myself. I don't see any reason why it wouldn't, but there may be configuration requirements in order to get them to work together properly.

**Comment by Urthen** [comment]
Closing this due to no further response - feel free to re-open if there are further questions.

**Comment by LouisWayne** [comment]
I just checked - it's not working with TypeScript
