### ISSUE TITLE
Can it abort webpack build process when found error?

### ISSUE THREAD

**Issue by somewind** [Urthen/case-sensitive-paths-webpack-plugin#44]
In my case, it found case sensitive error and printed out, but webpack still build success.

It caused CI not to report that error.

**Comment by Urthen** [comment]
This should absolutely cause Webpack to halt if it detects a case sensitive error. If you've changed webpack settings to not halt on errors, though, this plugin can't force a halt.

Can you share your webpack settings or a simple test case that shows how to get Webpack not to halt?

**Comment by Urthen** [comment]
Closing due to no further activity.
